services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - CARGO_BUILD_TARGET_DIR=/tmp/target
    volumes:
      - type: bind
        source: .
        target: /wip
